global using Club.AdminPanel.Domain.Domain.Club;
global using Club.AdminPanel.Domain.UiDefinitions.Customers;
global using Club.AdminPanel.Domain.UiDefinitions.Customers.CustomerSegments;
global using Club.AdminPanel.Domain.UiDefinitions.Customers.CustomerTenants;
global using Club.AdminPanel.Domain.UiDefinitions.Events;
global using Club.AdminPanel.Domain.UiDefinitions.Points;
global using Club.AdminPanel.Domain.UiDefinitions.Products;
global using Club.AdminPanel.Domain.UiDefinitions.Promotions;
global using Club.AdminPanel.Domain.UiDefinitions.Promotions.Base;
global using Club.AdminPanel.Domain.UiDefinitions.Surveys;
global using Club.Domain.Constants;
global using Club.Domain.Entities.Analytics;
global using Club.Domain.Entities.Common;
global using Club.Domain.Entities.Customers;
global using Club.Domain.Entities.CustomerSegments;
global using Club.Domain.Entities.Events;
global using Club.Domain.Entities.Feedback;
global using Club.Domain.Entities.Forum;
global using Club.Domain.Entities.Geography;
global using Club.Domain.Entities.Metrics;
global using CustomerProductMetrics = Club.Domain.Entities.Metrics.Data.CustomerProductMetrics;
global using Club.Domain.Entities.Points;
global using Club.Domain.Entities.Products;
global using Club.Domain.Entities.Promotions;
global using Club.Domain.Entities.Promotions.Data;
global using Club.Domain.Entities.Promotions.Enums;
global using Club.Domain.Entities.Promotions.Plans;
global using Club.Domain.Entities.Promotions.Surveys;
global using Club.Domain.Entities.Referal;
global using Club.Domain.Entities.Rewards;
global using Club.Domain.Entities.Tenants;
global using Club.Domain.Entities.Tenants.Data;
global using Club.Domain.Entities.Tenants.Enums;
global using Club.Domain.Enums;
global using CustomerReferrer = Club.Domain.Entities.Referal.CustomerReferrer;
global using CustomerSegment = Club.Domain.Entities.CustomerSegments.CustomerSegment;
global using CustomerSegmentMembership = Club.Domain.Entities.CustomerSegments.Data.CustomerSegmentMembership;
global using EventChannel = Club.Domain.Entities.Channels.EventChannel;
global using EventChannelValidEvent = Club.Domain.Entities.Channels.EventChannelValidEvent;
global using EventChannelValidIp = Club.Domain.Entities.Channels.EventChannelValidIp;
global using EventLog = Club.Domain.Entities.Events.Data.EventLog;
global using MetricValue = Club.Domain.Entities.Metrics.MetricValue;
global using PromotionEventReceived = Club.Domain.Entities.Promotions.Data.PromotionEventReceived;
global using PromotionParticipation = Club.Domain.Entities.Promotions.Data.PromotionParticipation;
global using PromotionRecipient = Club.Domain.Entities.Promotions.Data.PromotionRecipient;
global using ReferrerCode = Club.Domain.Entities.Referal.ReferrerCode;
global using Tenant = Club.Domain.Entities.Tenants.Tenant;
global using Neo.Bpms.Domain.Entities.Cmmn.UI;
global using Neo.Bpms.Domain.Features.Definitions.Entities;
global using Neo.Bpms.Domain.Features.MetaDefinitions.Dashboards;
global using Neo.Bpms.Domain.Features.MetaDefinitions.Entities;
global using Neo.Bpms.Domain.Features.MetaDefinitions.Forms;
global using Neo.Bpms.Domain.Features.MetaDefinitions.Projects;
global using Neo.Bpms.Domain.Features.MetaDefinitions.Reports;
global using Neo.Bpms.Domain.Model.Project;
global using Neo.Bpms.Domain.Model.UI.Forms;
global using Neo.Bpms.Domain.Models.Cmmn;
global using Neo.Bpms.Domain.Models.Cmmn.Common;
global using Neo.Bpms.Domain.Models.Cmmn.UI.Components;
global using Neo.Bpms.Domain.Models.Cmmn.UI.ConfiguredItems;
global using Neo.Bpms.Domain.Models.Cmmn.UI.Reports;
global using Neo.Bpms.MetaModel.ProcessData;
global using Neo.Domain.Entities.Base;
