<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\Club.Application\Club.Application.csproj" />
    <ProjectReference Include="..\..\Core\Club.Domain\Club.Domain.csproj" />
  </ItemGroup>

</Project>
